services:
  angular:
    image: list_client_app:${TAG:-latest}
    container_name: list_client_app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "85:80"
    restart: unless-stopped
    networks:
      - list_network

networks:
  list_network:
