services:
  angular:
    image: list_client_app:${TAG:-latest}
    container_name: list_client_app
    build:
      dockerfile: ./Dockerfile
    expose:
      - 80
    restart: unless-stopped
    networks:
      - dmz_network

networks:
  dmz_network:
    external: true
    name: network_dmz_network
