export const environment = {
    production: false,
    _BASE_URL: "http://localhost:8080/api/v1",
    _AUTH: "/auth",
    _ADMIN: "/admin",
    _PUBLIC: "/public",
    _USER: "/user",
    _AUTHENTIFICATE: "/authenticate",
    _REGISTER_LOG: "/register-log",
    _REGISTER_USER: "/register-user",
    _CATEGORY: "/category",
    _INVOICE: "/invoice",
    _MARKET: "/market",
    _SHOP: "/shop",
    _UPLOAD: "/upload",
    _READ: "/read",
    _READ_ALL: "/read/all",
    _CREATE: "/create",
    _DELETE: "/delete",
    _UPDATE: "/update",
    _THIS_USER: "/this/user",
    _AVATAR: "/avatar/"
}